---
- name: Install and configure Prometheus and Grafana
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - prometheus
          - grafana
        state: present

    - name: Start and enable Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Configure Prometheus (default config)
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

    - name: Restart Prometheus to apply configuration
      systemd:
        name: prometheus
        state: restarted

    - name: Configure Grafana to use Prometheus as a data source
      grafana_datasource:
        name: Prometheus
        type: prometheus
        url: http://localhost:9090
        access: proxy
        basic_auth: false
        json_data:
          http_method: POST
        admin: true
        state: present

    - name: Wait for Grafana to be fully up
      wait_for:
        port: 3000
        delay: 10

    - name: Create Grafana admin user (optional)
      community.grafana.grafana_user:
        name: admin
        password: admin
        email: admin@example.com
        role: Admin
        state: present
        permissions: admin

    - name: Ensure Grafana user is enabled
      community.grafana.grafana_user:
        name: admin
        state: present
        enabled: true
