---
- name: Setup Prometheus and Grafana
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Install Prometheus
      prometheus.prometheus.prometheus:
        state: present
        config:
          global:
            scrape_interval: "15s"
          scrape_configs:
            - job_name: "prometheus"
              static_configs:
                - targets: ["localhost:9090"]

    - name: Ensure Prometheus is running
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Install Grafana
      grafana.grafana.grafana:
        state: present
        url: http://localhost:3000
        admin_user: admin
        admin_password: admin
        grafana:
          server:
            root_url: /
            serve_from_sub_path: true
        users:
          - name: user
            email: user@example.com
            password: 123
            org_role: Admin

    - name: Add Prometheus as a data source in Grafana
      grafana.grafana.grafana_datasource:
        name: Prometheus
        type: prometheus
        access: proxy
        url: http://localhost:9090
        is_default: true
        basic_auth: false
        json_data:
          time_field: time
        secure_json_data: {}

    - name: Ensure Grafana is running
      systemd:
        name: grafana-server
        state: started
        enabled: yes
