name: AWS Provisioning

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Adjust this to your desired branch

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRV_KEY }}
  SSH_PUBLIC_KEY: ${{ vars.SSH_PUB_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  SSH_KEY_NAME: "github-actions-key"
  Instance_IP: ""

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Terraform
        id: cache-terraform
        uses: actions/cache@v4
        with:
          path: ~/.terraform
          key: terraform-${{ hashFiles('terraform.tf*') }}

      - name: Install Terraform
        if: steps.cache-terraform.outputs.cache-hit != 'true'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Process Terraform configuration
        env:
            TF_VAR_aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
            TF_VAR_aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
            TF_VAR_aws-region: ${{ env.AWS_REGION }} 
            TF_VAR_ssh-public-key: "${{ env.SSH_PUBLIC_KEY }}"
        run: |
             terraform init
             terraform validate
             terraform apply -auto-approve

      - name: Output instance IP
        run: |
              echo "Instance_IP=$(terraform output -json instance_ip | jq -r .)" >> $GITHUB_ENV
              echo "Instance IP: ${{ env.Instance_IP }}"

      - name: Verify connection
        id: verify-conn
        run: |
          echo "${{ env.SSH_PRIVATE_KEY }}" > tempkey-file
          chmod 600 tempkey-file

          if ssh -o StrictHostKeyChecking=no ubuntu@"${{ env.Instance_IP }}" -i tempkey-file; then
              echo "Connection successful!"
              exit 0
          else
              echo "Connection failed!"
              exit 1
          fi

          rm tempkey-file

      - name: Set up APT caching
        if: steps.verify-conn.outcome  == 'success'
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-cache.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install  Ansible
        run: |
            sudo apt-get update
            sudo apt-get install -y ansible

      - name: Verify Ansible Installation
        run: ansible --version

      - name: Run Ansible Playbook
        run: |
            cd ./ansible
            ansible-playbook -i "${{ env.INSTANCE_IP }}," main.yml --user=ubuntu
      
